mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-delete-field: option_status  # 全局逻辑删除的实体字段名
      logic-not-delete-value: 1
      logic-delete-value: 0
      id-type: auto