spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://120.79.132.251:3306/seata_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.75.115:8848
#        namespace: f81810bc-a134-4e55-955b-2d5c9c602826
#      config:
#        namespace: f81810bc-a134-4e55-955b-2d5c9c602826
  application:
    name: seata-account
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    com.formssi.account: debug
#    io.seata: debug

seata:
  tx-service-group: my_tx_group #与服务端保持一致
  service:
    vgroup-mapping:
      my_tx_group: default
    grouplist:
      default: 47.106.75.115:8091

# 可用配置
#seata:
#  enabled: true
#  service:
#    disable-global-transaction: false
#    grouplist:
#      default: 120.79.132.251:8091

#seata:
#  enabled: true
#  application-id: seata-account
#  config:
#    type: nacos
#    nacos:
#      server-addr: 120.79.132.251:8848
#      group: SEATA_GROUP
#      username: nacos
#      password: nacos
#  registry:
#    nacos:
#      server-addr: 120.79.132.251:8848
#      group: SEATA_GROUP
#      username: nacos
#      password: nacos
#      application: seata-server